### PR TITLE
Creates the backend.

### PR DESCRIPTION
**Pull request by nathan-lalli**
This is more than the title. It creates the backend for the system. It adds the models, routes, and controller.

I followed the tutorial that North gave us and then made it work for us.

Currently, we can do all of the regular CRUD operations on our database. We can make it do more as we find that we need more. 

It works as long as you have the local database on your machine.

### CODE REVIEW

**Review by ethanimooney — CHANGES_REQUESTED** [review]
I would remove DS_Store and add a .gitignore file to ignore that, node_modules, etc.

**Comment by ethanimooney** [comment]
Er, update the .gitignore

**Comment by nathan-lalli** [comment]
Made requested changes.

**Review by ethanimooney — APPROVED** [review]
Did you delete DS_Store?

**Pull request merged**
